/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts_bdl_ria;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author IT GRC
 */
public class pelanggan extends javax.swing.JFrame {

    private final String[] columns = {"id_pelanggan", "nama", "alamat", "no_telepon"};
    private final ArrayList<String[]> dataList = new ArrayList<>();
    Connection conn;
    Statement stmt;
    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/TOKO_BUKU";
    String user = "postgres";
    String password = "nidzom15";

    /**
     * Creates new form pelanggan
     */
    public pelanggan() {
        initComponents();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDpelanggan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabelPelanggan = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        cbFilter = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PELANGGAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID Pelanggan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nama Pelanggan");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Alamat");

        txtIDpelanggan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtAlamat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tbTabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabelPelanggan);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbFilter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Pelanggan", "Nama Pelanggan", "Alamat" }));
        cbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Search -->");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("No. Telepon");

        txtTelepon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnUpdate)
                                .addGap(28, 28, 28)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAlamat)
                            .addComponent(txtNama)
                            .addComponent(txtIDpelanggan)
                            .addComponent(txtTelepon))
                        .addGap(83, 83, 83)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnClear)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String id_pelanggan = txtIDpelanggan.getText();
        String nama = txtNama.getText();
        String alamat = txtAlamat.getText();
        String no_telepon = txtTelepon.getText();

        if (id_pelanggan.trim().isEmpty() && nama.trim().isEmpty() && alamat.trim().isEmpty() && no_telepon.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan data pelanggan terlebih dahulu");

        } else if (id_pelanggan.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan ID Pelanggan dulu!");
        } else if (nama.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Nama Pelanggan dulu!");
        } else if (alamat.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Alamat terlebih dulu!");
        } else if (no_telepon.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Nomer Telepon terlebih dulu!");
        } else {
            PreparedStatement preparedStatement;
            try {
                String sql = "INSERT INTO pelanggan (id_pelanggan, nama, alamat, no_telepon) VALUES (?, ?, ?, ?)";
                conn = DriverManager.getConnection(koneksi, user, password);
                preparedStatement = conn.prepareStatement(sql);

                preparedStatement.setLong(1, Long.parseLong(id_pelanggan));
                preparedStatement.setString(2, nama);
                preparedStatement.setString(3, alamat);
                preparedStatement.setLong(4, Long.parseLong(no_telepon));

                preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal ditambahkan", "Error", JOptionPane.ERROR_MESSAGE);
            }
            tampil();
            bersih();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id_pelanggan = txtIDpelanggan.getText();
        String nama = txtNama.getText();
        String alamat = txtAlamat.getText();
        String no_telepon = txtTelepon.getText();

        if (id_pelanggan.trim().isEmpty() && nama.trim().isEmpty() && alamat.trim().isEmpty() && no_telepon.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "update data pelanggan terlebih dahulu");

        } else if (id_pelanggan.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan ID Pelanggan dulu!");
        } else if (nama.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Nama Pelanggan dulu yang ingin di update!");
        } else if (alamat.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Alamat terlebih dulu yang ingin di update!");
        } else if (no_telepon.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Nomer Telepon terlebih dulu yang ingin di update");
        } else {
            PreparedStatement preparedStatement = null;
            try {
                String sql = "UPDATE pelanggan set nama =?, alamat =?, no_telepon =? WHERE id_pelanggan = ?";
                conn = DriverManager.getConnection(koneksi, user, password);
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, txtNama.getText());
                ps.setString(2, txtAlamat.getText());
                ps.setInt(3, Integer.parseInt(txtTelepon.getText()));
                ps.setInt(4, Integer.parseInt(txtIDpelanggan.getText()));

                int row = ps.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Update Berhasil");
                    tampil();
                    bersih();
                }

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id_pelanggan;
        id_pelanggan = txtIDpelanggan.getText();

        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            int jawab = JOptionPane.showConfirmDialog(null, "Silakan Konfirmasi?");
            switch (jawab) {
                case JOptionPane.YES_OPTION:
                    String deleteSql = "DELETE FROM pelanggan WHERE id_pelanggan = ?";
                    PreparedStatement ps = conn.prepareStatement(deleteSql);
                    ps.setInt(1, Integer.parseInt(txtIDpelanggan.getText()));
                    ps.executeUpdate();
                    ps.close();
                    conn.close();
                    bersih();
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(this, "Kamu menjawab tidak");
                    break;
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Cek Lagi!!!");

        }
        tampil();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        bersih();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tbTabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTabelPelangganMouseClicked
        int row = tbTabelPelanggan.getSelectedRow();
        txtIDpelanggan.setText(tbTabelPelanggan.getValueAt(row, 0).toString());
        txtNama.setText(tbTabelPelanggan.getValueAt(row, 1).toString());
        txtAlamat.setText(tbTabelPelanggan.getValueAt(row, 2).toString());
        txtTelepon.setText(tbTabelPelanggan.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbTabelPelangganMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        DefaultTableModel ob = (DefaultTableModel) tbTabelPelanggan.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        tbTabelPelanggan.setRowSorter(obj);
        int selectedIndex = cbFilter.getSelectedIndex();
        switch (selectedIndex) {
            case 0:
                obj.setRowFilter(RowFilter.regexFilter(txtSearch.getText(), 0));
                break;
            case 1:
                obj.setRowFilter(RowFilter.regexFilter(txtSearch.getText(), 1));
                break;
            case 2:
                obj.setRowFilter(RowFilter.regexFilter(txtSearch.getText(), 2));
                break;
            case 3:
                obj.setRowFilter(RowFilter.regexFilter(txtSearch.getText(), 3));
                break;
            default:
                break;
        }

    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dashboard p = new dashboard();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilterActionPerformed

    public final void tampil() {
        tbmmhs = new DefaultTableModel(new String[]{"ID Pelanggan", "Nama Pelanggan", "Alamat", "No. Telepon"}, 0);
        String sql = "SELECT * FROM pelanggan ORDER BY id_pelanggan";

        try {
            Class.forName(driver);
            try (var conn = DriverManager.getConnection(koneksi, user, password); Statement stmt = conn.createStatement()) {
                ResultSet rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    tbmmhs.addRow(new Object[]{
                        rs.getInt("id_pelanggan"),
                        rs.getString("nama").trim(),
                        rs.getString("alamat").trim(),
                        rs.getInt("no_telepon")
                    });
                    System.out.println(rs.getInt("id_pelanggan") + " " + rs.getString("nama") + " " + rs.getString("alamat") + " " + rs.getInt("no_telepon"));
                }
            }

        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbTabelPelanggan.setModel(tbmmhs);
    }
    DefaultTableModel tbmmhs;

    public void bersih() {
        txtIDpelanggan.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabelPelanggan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIDpelanggan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
